### ISSUE TITLE
Error with arguments when running against simple examples.

### ISSUE THREAD

**Issue by russleyshaw** [thlorenz/deoptigate#3]
Running against simple example in node v10.7 produces the error:
```
$ node -v
v10.7.0
$ deoptigate isolate-0000021C90C8FC40-v8.log
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
```

**Comment by markthethomas** [comment]
Having this same issue and it fails to resolve the file (w/ the same error). Would love to either help fix this bit or something - this is a super cool project, excited to use it! 🎉

**Comment by markthethomas** [comment]
Looks like it's getting a `null` key arg when hitting the root of the folder?

```js
async function resolveAll(set, root) {
  const files = new Map()
  for (const key of set) {
      const fullPath = path.resolve(root, key) // here; added a guard and seems to resolve
      const relativePath = path.relative(root, fullPath)
      if (!(await canRead(fullPath))) continue
      if (!(await stat(fullPath)).isFile()) continue
      const src = await readFile(fullPath, 'utf8')
      files.set(key, { fullPath, relativePath, src })
  }
  return files
}
```

I added a guard around `key` and it works, but I assume there's a better upstream solution. Happy to look into it more

**Comment by thlorenz** [comment]
Ah odd, maybe this should be fixed in [files-provider](https://github.com/thlorenz/files-provider) which is basically trying to resolve the log files?

I'm not entirely sure what's going on, but if you have a `*.log` file in the folder you run `deoptigate` in then it should work ...

Aside from fixing that, as I said I'm working on an even simpler solution ATM :)

**Comment by markthethomas** [comment]
yeah it looks like the `key` arg is coming back w/ null, which looks like it's encountering when at the root of the project. This was running w/ only 1 isolate file in there and nothing crazy. Works w/ the guard and/or fixing the null `key` 👍

**Comment by thlorenz** [comment]
OK, open to PRs that keep things from crashing :)

**Comment by markthethomas** [comment]
💯 I'll have one up tomorrow!

**Comment by markthethomas** [comment]
hey sorry this took longer than expected, but really simple change is here: https://github.com/thlorenz/deoptigate/pull/4

**Comment by thlorenz** [comment]
Closing for now (see #4).
